<?php

namespace App\Application\Facilities\Services;

use App\Application\Facilities\DTOs\FacilityData;
use App\Domain\Facilities\Entities\FacilityEntity;
use App\Domain\Facilities\Exceptions\FacilityDuplicateException;
use App\Domain\Facilities\Exceptions\FacilityRequiredFieldsException;
use App\Domain\Facilities\Repositories\FacilityRepositoryInterface;

class CreateFacilityService
{
    public function __construct(
        private readonly FacilityRepositoryInterface $facilityRepository
    ) {
    }

    public function execute(FacilityData $data): FacilityEntity
    {
        // Business Rule: Required Fields
        if (empty(trim($data->name)) || empty(trim($data->location)) || empty(trim($data->facilityType))) {
            throw new FacilityRequiredFieldsException();
        }

        // Business Rule: Uniqueness
        if ($this->facilityRepository->existsByNameAndLocation($data->name, $data->location)) {
            throw new FacilityDuplicateException();
        }

        // Create entity
        $facility = new FacilityEntity(
            name: $data->name,
            location: $data->location,
            facilityType: $data->facilityType,
            capabilities: $data->capabilities,
            description: $data->description,
            partnerOrganization: $data->partner_organization,
            facilityCode: null,  // Will be generated by model
            facility_id: null,   // Will be generated by model
        );

        // Persist to database
        return $this->facilityRepository->create($facility);
    }
}